### ISSUE TITLE
Car Purchasing Prediction

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#1]
- Project Title : Car Purchasing Prediction
- Aim : Predict which are the cars to be purchased.
- Dataset : https://www.kaggle.com/datasets/gabrielsantello/cars-purchase-decision-dataset
- Approach : Try to use 2-3 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**Guidelines to be followed**

- You need to create a separate folder named as the Project Title.
- Inside that folder, there will be four main components.
- Images - To store the required images.
- Dataset - To store the dataset or, information/source about the dataset.
- Model - To store the machine learning model you've created using the dataset.
- requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
- Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.

**Happy Contributing**

**Comment by JanhaviGadre** [comment]
Name: Janhavi Gadre
College: Cummins College of Engineering for women
Department: Computer
“I would like to work on this issue”

**Comment by mrunal736** [comment]
I have assigned you this issue
Only after completion of this issue you will be assigned next issue 
Make sure to make pull request in 2 days
Happy Coding!

**Comment by mrunal736** [comment]
You haven't followed the guidelines properly 
Create a separate folder of project title which has sub folders dataset , model , images, requirements.txt
You can refer sample folder 
Don't create folder  inside sample create a separate one

**Comment by JanhaviGadre** [comment]
I have done the changes....can you check now

**Comment by JanhaviGadre** [comment]
Can you please check and tell?
