### ISSUE TITLE
Chocolate Ratings Analysis

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#2]
**Project Title : Chocolate Ratings Analysis**

-  Aim : This project will analyze the data of  ratings of chocolate
-  Dataset : https://www.kaggle.com/datasets/andrewmvd/chocolate-ratings
-  Approach : Try to use 2-3 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**Guidelines to be followed**

- You need to create a separate folder named as the Project Title.
- Inside that folder, there will be four main components.
- Images - To store the required images.
- Dataset - To store the dataset or, information/source about the dataset.
- Model - To store the machine learning model you've created using the dataset.
- requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
- Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.

**Happy Contributing**

**Comment by AnnadaD** [comment]
Annada Dash
Cummins College of Engineering for Women, Pune
Dept- Comp
I would like to work on this issue
Can you please assign me this issue?

**Comment by mrunal736** [comment]
I have assigned you this issue
Only after completion of this issue you will be assigned next issue
Make sure to make pull request in 2 days
Happy Coding!

**Comment by AnnadaD** [comment]
Hi @mrunal736 I am unable to visit the dataset link page, can you please check if there is some issue with it?

**Comment by mrunal736** [comment]
I've updated the issue , since there was some problem with the dataset link. I'll extend the time period to work by one day.
