### ISSUE TITLE
Students Performance in Exams Dataset Readme

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#20]
- Dataset Link: https://www.kaggle.com/datasets/whenamancodes/students-performance-in-exams
- Download exams.csv file from given link
- upload it inside Students Performance in Exams/Dataset 
- Update Students Performance in Exams/Dataset/Readme.md. Write details about the dataset.

**Comment by shreya2208** [comment]
Shreya Amritkar
Cummins College of Engineering for Women, Pune
Dept- Information Technology 3rd year
I would like to work on this issue, can u pls assign it to me?

**Comment by mrunal736** [comment]
Make pull request by tonight, happy contributing!

**Comment by mrunal736** [comment]
i hope you are working on this issue , make pull request as soon as possible

**Comment by Sakshi778** [comment]
Sakshi Khaire
CCOEW Pune
Comp TY
I would like to work on this issue.
