### ISSUE TITLE
Students Performance in Exams Model EDA

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#21]
- Dataset Link: Students Performance in Exams: https://www.kaggle.com/datasets/whenamancodes/students-performance-in-exams
- Perform Exploratory Data Analysis on given dataset
- Inside Students Performance in Exams /Model create a file eda.ipynb 
- Upload all images in Students Performance in Exams /Images folder

**Comment by AnnadaD** [comment]
Hello,
Annada Dash
CCOEW
SY Comp
I want to work on this issue
Can you please assign this to me

**Comment by Asmita-Jadhav02** [comment]
Hello,
Asmita Jadhav
CCOEW
TY Comp
I would like to work on this issue
Please assign this to me

**Comment by mrunal736** [comment]
> Hello, Annada Dash CCOEW SY Comp I want to work on this issue Can you please assign this to me

Make pull request by tonight , happy contributing!

**Comment by mrunal736** [comment]
@AnnadaD you are already assigned to an issue , after the issue is closed you will be assigned to next one

**Comment by AnnadaD** [comment]
okay.

**Comment by mrunal736** [comment]
@Asmita-Jadhav02  i've assigned you this issue , make pull request by tonight , happy contributing!
