### ISSUE TITLE
Netflix Movies and TV shows EDA

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#22]
- Dataset Link: https://www.kaggle.com/datasets/shivamb/netflix-shows
- Perform Exploratory Data Analysis on given dataset
- Inside Netflix Movies and TV shows/Model create a file eda.ipynb
- Upload all images in Netflix Movies and TV shows /Images folder

**Comment by utkarshaskumbhar** [comment]
I am utkarsha from CCOEW sy comp
Please assign me this issue

**Comment by Asmita-Jadhav02** [comment]
Hello,
Asmita Jadhav
CCOEW
TY Comp
I would like to work on this issue
Please assign this to me

**Comment by mrunal736** [comment]
Make pull request by tonight , happy contributing
