### ISSUE TITLE
Netflix Movies and TV shows Readme

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#23]
- Dataset Link : https://www.kaggle.com/datasets/shivamb/netflix-shows
- Download netflix_titles.csv file from given link
- upload it inside Netflix Movies and TV shows /Dataset
- Update Netflix Movies and TV shows /Dataset/Readme.md. Write details about the dataset.

**Comment by ShreyaShetty263** [comment]
pl assign me this

**Comment by mrunal736** [comment]
Make pull request by 4pm today, happy contributing!
