### ISSUE TITLE
Credit Card Fraud Detection Readme

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#24]
- Dataset Link:https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
- Download creditcard.csv file from given link
- upload it inside Credit Card Fraud Detection/Dataset
- Update Credit Card Fraud Detection/Dataset/Readme.md. Write details about the dataset.
- Star the repository

**Comment by ShreyaShetty263** [comment]
please assign me this

**Comment by siddhesh-desai** [comment]
Hello @mrunal736 please assign it to me.

**Comment by mrunal736** [comment]
You are assigned to an issue , once that issue is closed you will be assigned next issue

> Shreya shetty ccoew entc pl assign me this

**Comment by mrunal736** [comment]
> Hello @mrunal736 please assign it to me.

can you pls comment 
Name,College and year

**Comment by harshyadavcs** [comment]
Can I directly make a pr or do I have to get assigned first for this? I want to work on this. And do you mean creditcard.csv  because I could not able to find exams.csv on the given link.

**Comment by Zweak** [comment]
Hey @mrunal736 I can work on this issue. Can you assign me?
Pushkar Zalte
PVGCOE comp, Last year

**Comment by siddhesh-desai** [comment]
Siddhesh Desai, VIT Pune, Second Year

**Comment by mrunal736** [comment]
> Siddhesh Desai, VIT Pune, Second Year

Make pull request by tonight , happy contributing!

**Comment by mrunal736** [comment]
> Can I directly make a pr or do I have to get assigned first for this? I want to work on this. And do you mean creditcard.csv because I could not able to find exams.csv on the given link. @mrunal736 

for all the issues under the repositories of gdsc ccoew it is mandatory to get the issue assigned.

**Comment by mrunal736** [comment]
If the pull request is not made by tonight i will assign the issue to next person who has commented

**Comment by siddhesh-desai** [comment]
Issue solved. Please have a look at #24
