### ISSUE TITLE
Cryptocurrency Prices EDA

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#26]
- Dataset Link: https://www.kaggle.com/datasets/sudalairajkumar/cryptocurrencypricehistory
- Perform Exploratory Data Analysis on given dataset
- Inside Cryptocurrency Prices/Model create a file eda.ipynb
- Upload all images in Cryptocurrency Prices /Images folder
- Star the repository

**Comment by Asmita-Jadhav02** [comment]
Hello,
Asmita Jadhav
CCOEW
TY Comp
I would like to work on this issue
Please assign this to me

**Comment by mrunal736** [comment]
Make pull request by tonight , happy contributing!
