### ISSUE TITLE
Cryptocurrency Prices Readme

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#27]
- Dataset Link: https://www.kaggle.com/datasets/sudalairajkumar/cryptocurrencypricehistory
- Download coin_Aave.csv file from given link
- upload it inside Cryptocurrency Prices/Dataset
- Update Cryptocurrency Prices/Dataset/Readme.md. Write details about the dataset.

**Comment by Zweak** [comment]
Pushkar Zalte, Pvg Nashik, Last Year
can you assign?

**Comment by mrunal736** [comment]
make pull request by tonight , happy contributing!
