### ISSUE TITLE
Iris Classification

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#3]
**Project Title : Iris Classification**

- Aim : Implement a machine learning classification or regression model on the dataset. Classification is the task of separating items into its corresponding class.
- Dataset : https://archive.ics.uci.edu/ml/datasets/Iris
- Approach : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**Guidelines to be followed**

- You need to create a separate folder named as the Project Title.
- Inside that folder, there will be four main components.
- Images - To store the required images.
- Dataset - To store the dataset or, information/source about the dataset.
- Model - To store the machine learning model you've created using the dataset.
- requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
- Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.

**Happy Contributing**

**Comment by JanhaviGadre** [comment]
Name: Janhavi Gadre
College: Cummins College of Engineering for women
Department: Computer 
“I would like to work on this issue”
Can you please assign me this issue?

**Comment by AnnadaD** [comment]
Annada Dash
Cummins College of Engineering for Women, Pune
Dept- Comp
I would like to work on this issue
Can you please assign me this issue?

**Comment by JanhaviGadre** [comment]
I would like to work on this issue.
can you please assign me this issue?

**Comment by mrunal736** [comment]
I have closed this issue for some reason,  I'll be adding more today.
