### ISSUE TITLE
Red Wine Quality review readme

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#40]
- Dataset Link: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/
- Download winequality-red.csv file from given link
- upload it inside Red Wine Quality review/Dataset
- Update Red Wine Quality review/Dataset/Readme.md. Write details about the dataset.

**Comment by OjasiG** [comment]
Ojasi Gokhale
CCOEW
TY Comp
Can you assign me this issue?

**Comment by mrunal736** [comment]
Make pull request by tonight, happy contributing!
