### ISSUE TITLE
Breast Cancer Detection Dataset details

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#42]
- Dataset Link: https://www.kaggle.com/datasets/whenamancodes/students-performance-in-exams
- Download breast-cancer.csv file from given link upload it inside Breast Cancer Detection /Dataset
- Update Breast Cancer Detection/Dataset/Readme.md. Write details about the dataset.

**Comment by Sakshi778** [comment]
Sakshi Khaire
CCOEW
Comp TY
I would like to work on this issue
