### ISSUE TITLE
Redwine quality review eda

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#43]
- Dataset Link: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/
- Perform Exploratory Data Analysis on given dataset

- Inside Red Wine Quality review/Model create a file eda.ipynb

- Upload all images in Red Wine Quality review/Images folder

**Comment by OjasiG** [comment]
Ojasi Gokhale
CCOEW
TY Comp
Can you please assign this issue to me?
