### ISSUE TITLE
White Wine Quality Review 

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#47]
- Dataset Link: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/
- Download winequality-white.csv file from given link
- upload it inside Red Wine Quality review/Dataset
- Update White Wine Quality review/Dataset/Readme.md. Write details about the dataset.

**Comment by Sakshi778** [comment]
Sakshi Khaire
CCOEW
Comp TY
I would like to work on this issue.
