### ISSUE TITLE
Pizza price prediction dataset

### ISSUE THREAD

**Issue by mrunal736** [Google-Developer-Student-Club-CCOEW/AI-ML#48]
- Dataset Link: https://www.kaggle.com/datasets/knightbearr/pizza-price-prediction-real-data

- Download .csv file from given linkupload it inside Pizza price prediction/Dataset

- Update Pizza price prediction/Dataset/Readme.md. Write details about the dataset.

**Comment by Sakshi778** [comment]
Sakshi Khaire
CCOEW
Comp TY
I would like to work on this issue.
