### ISSUE TITLE
Add Performance Metrics

### ISSUE THREAD

**Issue by ParnaviKulkarni** [Google-Developer-Student-Club-CCOEW/AI-ML#6]
Write code to analysis the detection results.
Following metrics need to be programmed:
* Accuracy Score
* Confusion Matrix
* Precision
* Recall
* F1 Score

You may add more metrics as you wish in addition to those mentioned above.

**_Dataset is inside AI-ML/data directory.
Project code is inside AI-ML/code directory.
Add your code inside ''Model Accuracy Checking" section_**

**Comment by ishashukla183** [comment]
Isha Shukla TY Comp C
Could you assign this issue to me?

**Comment by ParnaviKulkarni** [comment]
I have assigned you this issue
Only after completion of this issue you will be assigned next issue
Make sure to make pull request in 2 days
Happy Coding!

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
Cummins college of engineering for women, pune
Dept: Electronics and telecommunication
I would like to work on this issue. Can you please assign me this issue?
